
all:
	$(MAKE) -C utils
	$(MAKE) -C bbm
	$(MAKE) -C dmp
	$(MAKE) -C ks
	$(MAKE) -C ks_imp
	$(MAKE) -C pure
	$(MAKE) -C supp_enum_dbl
	$(MAKE) -C ts

clean:
	$(MAKE) clean -C utils
	$(MAKE) clean -C bbm
	$(MAKE) clean -C dmp
	$(MAKE) clean -C ks
	$(MAKE) clean -C ks_imp
	$(MAKE) clean -C pure
	$(MAKE) clean -C supp_enum_dbl
	$(MAKE) clean -C ts

